#!/usr/bin/env python3
import os
import subprocess
import json
import re
from datetime import datetime
from pathlib import Path

def run_cmd(cmd):
    try:
        return subprocess.check_output(cmd, shell=True, stderr=subprocess.STDOUT).decode('utf-8').strip()
    except: return "Error executing command"

def main():
    report_path = Path("docs/M-SECURITY(legion-windows).md")
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    report = f"# M-SECURITY Audit (legion-windows)\n"
    report += f"**Timestamp:** {timestamp}\n"
    report += f"**OS:** Windows 11\n\n"
    
    report += "## 1. Executive Summary\n"
    report += "This report provides a technical analysis of the security posture and data privacy controls for the M-Gemini archival flow on the Windows partition.\n\n"
    
    report += "## 2. Infrastructure Security\n"
    git_user = run_cmd("git config user.name")
    git_email = run_cmd("git config user.email")
    remotes = run_cmd("git remote -v")
    branch = run_cmd("git branch --show-current")
    report += f"### 2.1 Git Configuration\n- **Git Identity:** {git_user} ({git_email})\n- **Active Branch:** {branch}\n- **Remotes:**\n```text\n{remotes}\n```\n\n"
    
    report += "## 3. Data Privacy & Redaction Efficacy\n"
    pii_patterns = [
        r"\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b",
        r"sk-[a-zA-Z0-9]{20,}",
        r"ghp_[a-zA-Z0-9]{20,}"
    ]
    
    leaks = []
    log_dir = Path("chat_logs")
    if log_dir.exists():
        for log_file in log_dir.glob("*.json"):
            with open(log_file, 'r', encoding='utf-8', errors='ignore') as f:
                content = f.read()
                for pattern in pii_patterns:
                    if re.search(pattern, content):
                        leaks.append(f"{log_file.name} matched {pattern}")
    
    status = "[PASS] No raw PII/Secrets detected." if not leaks else f"[FAIL] {len(leaks)} potential leaks detected."
    report += f"- **Redaction Status:** {status}\n\n"
    
    report += "## 4. System & Network State\n"
    listeners = run_cmd("netstat -ano | findstr LISTENING").split('\n')[:10]
    report += "### 4.1 Active Network Listeners (Top 10)\n```text\n" + '\n'.join(listeners) + "\n```\n\n"
    
    processes = run_cmd("tasklist /FI \"STATUS eq RUNNING\"").split('\n')[:20]
    report += "### 4.2 Running Processes (Partial)\n```text\n" + '\n'.join(processes) + "\n```\n\n"
    
    report += "## 5. File System Permissions\n"
    acl = run_cmd("icacls .").split('\n')[:10]
    report += "### 5.1 Directory Permissions (icacls)\n```text\n" + '\n'.join(acl) + "\n```\n\n"
    
    report += "## 6. Recommendations\n"
    report += "1. **GPG Signing**: Ensure GPG signing is enforced for all commits on the Windows partition.\n"
    report += "2. **Environment Isolation**: Periodically rotate the Git push tokens used for automated archival.\n"
    report += "3. **Audit Frequency**: Run this script after every major system update.\n\n"
    report += "---\n*Audit generated by Gemini CLI Agent.*\n"
    
    with open(report_path, 'w', encoding='utf-8') as f:
        f.write(report)
    print(f"Audit complete. Report saved to {report_path}")

if __name__ == "__main__":
    main()
