$reportPath = "docs/M-SECURITY(legion-windows).md"
$timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"

$header = "# M-SECURITY Audit (legion-windows)`n**Timestamp:** $timestamp`n**Host:** $env:COMPUTERNAME`n**OS:** Windows 11 ($([System.Environment]::OSVersion))"
$summary = "`n`n## 1. Executive Summary`nThis report provides a technical analysis of the security posture and data privacy controls for the M-Gemini archival flow on the Windows partition."

$gitUser = git config user.name
$gitEmail = git config user.email
$remotes = git remote -v
$branch = git branch --show-current
$infra = "`n`n## 2. Infrastructure Security`n### 2.1 Git Configuration`n- **Git Identity:** $gitUser ($gitEmail)`n- **Active Branch:** $branch`n- **Remotes:**`n  ```text`n$remotes`n  ```"

$piiPatterns = @(
    "\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b", 
    "sk-[a-zA-Z0-9]{20,}",                                
    "ghp_[a-zA-Z0-9]{20,}"                                
)

$leaks = @()
foreach ($pattern in $piiPatterns) {
    try {
        $matches = Select-String -Path "chat_logs/*.json" -Pattern $pattern -ErrorAction SilentlyContinue
        if ($matches) { $leaks += $matches }
    } catch {}
}

$privacyStatus = if ($leaks.Count -eq 0) { "[PASS] No raw PII/Secrets detected in chat_logs/." } else { "[FAIL] Potential leaks detected in $($leaks.Count) instances." }
$privacy = "`n`n## 3. Data Privacy & Redaction Efficacy`n- **Redaction Status:** $privacyStatus"

$listeners = netstat -ano | Select-String "LISTENING" | Select-Object -First 10 | Out-String
$syncProcesses = Get-Process | Where-Object { $_.ProcessName -match "git|python|ssh|gemini" } | Select-Object ProcessName, Id, CPU | Out-String
$network = "`n`n## 4. System & Network State`n### 4.1 Active Network Listeners (Top 10)`n```text`n$listeners`n```"
$processes = "`n### 4.2 Relevant Processes`n```text`n$syncProcesses`n```"

$acl = Get-Acl . | Select-Object -ExpandProperty Access | Select-Object IdentityReference, FileSystemRights -First 5 | Out-String
$fs = "`n`n## 5. File System Permissions`n### 5.1 Repository ACLs`n```text`n$acl`n```"

$recs = "`n`n## 6. Recommendations`n1. **GPG Signing**: Ensure GPG signing is enforced for all commits on the Windows partition.`n2. **Environment Isolation**: Periodically rotate the Git push tokens used for automated archival.`n3. **Audit Frequency**: Run this script after every major system update.`n`n---`n*Audit generated by Gemini CLI Agent.*"

$fullReport = $header + $summary + $infra + $privacy + $network + $processes + $fs + $recs
$fullReport | Out-File -FilePath $reportPath -Encoding utf8
Write-Host "Audit complete."
